<?php
    /* @see Ebizmarts_SagePaySuite_Block_Checkout_Surcharge */
?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getSurchargetotal()) ?>
    </td>
</tr>